---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r}
data1 <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r, fig.height=10, fig.width=10}
library(ggplot2)
totalSteps <- tapply(data1$steps, data1$date, FUN=sum, na.rm=TRUE)  ##Calculate the total steps by date.
qplot(totalSteps,xlab = "Total Steps for each day",main = "Plot for Total Steps for each day")
```

```{r}
mean(totalSteps,na.rm=TRUE)
median(totalSteps, na.rm = TRUE)
```

## What is the average daily activity pattern?
```{r}
library(ggplot2)
library(plyr)
averageStep <- ddply(data1, c("interval"), summarise, mean = mean(steps,na.rm = TRUE))
colnames(averageStep)[2]<-"meanStep" ##Rename the Steps column
ggplot(data=averageStep, aes(x=interval, y=meanStep)) + 
        geom_line() +
        xlab("5-minute interval") +
        ylab("average number of steps taken")
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
